GET http://localhost:8000/api/numerical_operations?a=1&b=2&op=add
Accept: application/json


###
http://localhost:8000/api/numerical_operations?a=5000000000000000&b=0&op=divide

###

GET http://127.0.0.1:8000/api/newtons_method?f_string=x%2A%2A2%20-%203%20%2B%201&df_string=x%2A2&x0=-2.0
Accept: application/json

###


GET http://127.0.0.1:8000/api/simple_iteration?f_string=x%2A%2A2%20-%203%20%2B%201&x0=-2.0

