name: Build and deploy client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0

      - name: Install dependencies
        run: yarn
        working-directory: ${{env.working-directory}}

      - name: Build
        run: yarn build --base-href /Numerical-Methods-Labs/
        working-directory: ${{env.working-directory}}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: client/dist/client

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
